// Fit the shipped default calibration (ADR 0010) and regenerate
// src/analysis/defaultCalibration.ts.
//
// Reuses the production pipeline byte-for-byte — gatherCached → evaluateRun →
// calibrationPoints → fitCalibrationSet — pooled across the shared reference
// locations, with run dates spread over the usable archive window. Most models
// are archived only from 2 April 2026, so seasonal coverage grows as the archive
// deepens: regenerate periodically.
//
// Run with:  pnpm dlx tsx scripts/fit-default-calibration.ts [--cache-dir <path>]
//   --cache-dir : reuse (and top up) a directory of cached RunEvaluation JSON
//                 instead of re-fetching; defaults to the shared cache the
//                 weight scripts fill (see scripts/lib/collectRuns).
// (Node's global fetch; the api layer's localStorage guard makes it free-tier.)

import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { calibrationPoints } from "@/analysis/calibrationSample";
import type { RunRef } from "@/analysis/collectSample";
import type { RunEvaluation } from "@/analysis/runEvaluation";
import { fitCalibrationSet, type CalibrationSet } from "@/domain/calibration";
import { LEAD_BANDS } from "@/domain/scorecard";
import { VERIFIED_VARIABLES } from "@/domain/verification";

import { cacheDirFromArgv, gatherCached, runDates } from "./lib/collectRuns";
import { REFERENCE_LOCATIONS } from "./lib/referenceLocations";

/** Runs per location, spread evenly across the usable archive window. */
const RUNS_PER_LOCATION = 8;

/** Truth needs ERA5 to cover run+7d with its ~5-day lag; 14 is comfortably safe. */
const TRUTH_LAG_DAYS = 14;

function bandCounts(set: CalibrationSet): string {
  return VERIFIED_VARIABLES.map((v) => `${v}: [${set[v].bands.map((b) => b?.n ?? "-").join(", ")}]`).join("  ");
}

async function main(): Promise<void> {
  const cacheDir = cacheDirFromArgv();
  const dates = runDates(RUNS_PER_LOCATION, TRUTH_LAG_DAYS);
  const refs: RunRef[] = dates.map((runDate) => ({ runDate, runHour: 0 }));
  console.log(`Cache dir: ${cacheDir}`);
  console.log(`Reference run dates: ${dates.join(", ")}`);

  const allRuns: RunEvaluation[] = [];
  for (const location of REFERENCE_LOCATIONS) {
    const t0 = Date.now();
    // eslint-disable-next-line no-await-in-loop -- sequential per location on purpose: polite to open-meteo's free tier.
    const runs = await gatherCached(location, refs, { cacheDir });
    allRuns.push(...runs);
    console.log(`${location.name.padEnd(12)} ${runs.length}/${refs.length} runs evaluated in ${((Date.now() - t0) / 1000).toFixed(0)}s`);
  }

  const points = calibrationPoints(allRuns);
  const set = fitCalibrationSet(points, undefined, "builtin");
  const perVariable = Object.fromEntries(VERIFIED_VARIABLES.map((v) => [v, points.filter((p) => p.variable === v).length]));
  console.log(`\n${points.length} calibration points (${JSON.stringify(perVariable)})`);
  console.log(`Fitted bands (n per ${LEAD_BANDS.map((b) => b.label).join(" / ")}):  ${bandCounts(set)}`);

  for (const v of VERIFIED_VARIABLES) {
    if (set[v].bands.every((b) => b === null)) console.warn(`WARNING: no band cleared the data gate for ${v} — default tier will not cover it.`);
  }

  const meta = {
    generatedAt: new Date().toISOString(),
    locations: REFERENCE_LOCATIONS.map((l) => l.name),
    runDates: dates,
    points: perVariable,
  };

  const outPath = join(dirname(fileURLToPath(import.meta.url)), "..", "src", "analysis", "defaultCalibration.ts");
  writeFileSync(
    outPath,
    `// GENERATED by scripts/fit-default-calibration.ts — do not edit by hand.
// The shipped default calibration tier (ADR 0010): curves fitted offline from
// verification samples at global reference locations, slotted into the ladder
// below the device tiers. Regenerate with:
//   pnpm dlx tsx scripts/fit-default-calibration.ts

import type { CalibrationSet } from "@/domain/calibration";

export interface DefaultCalibrationMeta {
  generatedAt: string;
  locations: string[];
  runDates: string[];
  /** Calibration points consumed, per variable. */
  points: Record<string, number>;
}

export const DEFAULT_CALIBRATION_META: DefaultCalibrationMeta | null = ${JSON.stringify(meta, null, 2)};

export const DEFAULT_CALIBRATION: CalibrationSet | null = ${JSON.stringify(set, null, 2)};
`,
  );
  console.log(`\nWrote ${outPath}`);
}

await main();
