// GENERATED by scripts/fit-default-calibration.ts — do not edit by hand.
// The shipped default calibration tier (ADR 0010): curves fitted offline from
// verification samples at global reference locations, slotted into the ladder
// below the device tiers. Regenerate with:
//   pnpm dlx tsx scripts/fit-default-calibration.ts

import type { CalibrationSet } from "@/domain/calibration";

export interface DefaultCalibrationMeta {
  generatedAt: string;
  locations: string[];
  runDates: string[];
  /** Calibration points consumed, per variable. */
  points: Record<string, number>;
}

export const DEFAULT_CALIBRATION_META: DefaultCalibrationMeta | null = {
  generatedAt: "2026-07-10T17:25:51.172Z",
  locations: ["Munich", "London", "Lisbon", "Oslo", "New York", "Denver", "Seattle", "Tokyo", "Singapore", "Sydney", "São Paulo", "Cape Town"],
  runDates: ["2026-04-02", "2026-04-14", "2026-04-26", "2026-05-08", "2026-05-21", "2026-06-02", "2026-06-14", "2026-06-26"],
  points: {
    temperature_2m: 672,
    precipitation: 672,
  },
};

export const DEFAULT_CALIBRATION: CalibrationSet | null = {
  temperature_2m: {
    bands: [
      {
        bins: [
          {
            raw: 0.013414512179710288,
            p: 0.8244047619047619,
          },
          {
            raw: 0.07246827717430718,
            p: 0.8970315398886827,
          },
          {
            raw: 0.12288586493200822,
            p: 0.8970315398886827,
          },
          {
            raw: 0.1924170184116579,
            p: 0.9196428571428571,
          },
          {
            raw: 0.3489299977318901,
            p: 0.9912790697674418,
          },
        ],
        n: 192,
        source: "builtin",
      },
      {
        bins: [
          {
            raw: 0.17468359173573395,
            p: 0.777281746031746,
          },
          {
            raw: 0.31807641704276807,
            p: 0.9092431193760097,
          },
          {
            raw: 0.4183861813722298,
            p: 0.9092431193760097,
          },
          {
            raw: 0.49854064325196495,
            p: 0.9677579365079365,
          },
          {
            raw: 0.5932433292578823,
            p: 0.991763565891473,
          },
        ],
        n: 192,
        source: "builtin",
      },
      {
        bins: [
          {
            raw: 0.28831810197562446,
            p: 0.6236338797814207,
          },
          {
            raw: 0.45054454221169704,
            p: 0.6458333333333333,
          },
          {
            raw: 0.5329586630562367,
            p: 0.787568306010929,
          },
          {
            raw: 0.6114274062622049,
            p: 0.8393817204301075,
          },
          {
            raw: 0.6800953253211556,
            p: 0.9038978494623655,
          },
        ],
        n: 288,
        source: "builtin",
      },
    ],
  },
  precipitation: {
    bands: [
      {
        bins: [
          {
            raw: 0.7121454515203854,
            p: 0.797681039048582,
          },
          {
            raw: 0.8829890533206758,
            p: 0.797681039048582,
          },
          {
            raw: 0.9436302626416818,
            p: 0.797681039048582,
          },
          {
            raw: 0.9659994719717945,
            p: 0.9151785714285714,
          },
          {
            raw: 0.9966911221669447,
            p: 0.9869186046511628,
          },
        ],
        n: 192,
        source: "builtin",
      },
      {
        bins: [
          {
            raw: 0.8090690296558698,
            p: 0.8242940199335548,
          },
          {
            raw: 0.9479134422626728,
            p: 0.8242940199335548,
          },
          {
            raw: 0.9841711730355512,
            p: 0.8242940199335548,
          },
          {
            raw: 0.9974587891229817,
            p: 0.9895833333333334,
          },
          {
            raw: 1,
            p: 0.9898255813953488,
          },
        ],
        n: 192,
        source: "builtin",
      },
      {
        bins: [
          {
            raw: 0.8524122055836453,
            p: 0.7026959638460339,
          },
          {
            raw: 0.9462575503435392,
            p: 0.7026959638460339,
          },
          {
            raw: 0.982057982261206,
            p: 0.7249544626593807,
          },
          {
            raw: 0.994571577161013,
            p: 0.9068100358422939,
          },
          {
            raw: 0.9999599936997979,
            p: 0.9874551971326164,
          },
        ],
        n: 288,
        source: "builtin",
      },
    ],
  },
};
