// GENERATED by scripts/fit-default-calibration.ts — do not edit by hand.
// The shipped default calibration tier (ADR 0010): curves fitted offline from
// verification samples at global reference locations, slotted into the ladder
// below the device tiers. Regenerate with:
//   pnpm dlx tsx scripts/fit-default-calibration.ts

import type { CalibrationSet } from "@/domain/calibration";

import { currentAnalysis } from "./version";

export interface DefaultCalibrationMeta {
  analysisVersion: number;
  generatedAt: string;
  locations: string[];
  runDates: string[];
  /** Calibration points consumed, per variable. */
  points: Record<string, number>;
}

const FITTED_META: DefaultCalibrationMeta | null = {
  analysisVersion: 4,
  generatedAt: "2026-09-13T13:35:02.841Z",
  locations: ["Munich", "London", "Lisbon", "Oslo", "New York", "Denver", "Seattle", "Tokyo", "Singapore", "Sydney", "São Paulo", "Cape Town"],
  runDates: ["2026-04-02", "2026-04-23", "2026-05-14", "2026-06-04", "2026-06-26", "2026-07-17", "2026-08-07", "2026-08-28"],
  points: {
    temperature_2m: 960,
    precipitation: 864,
  },
};

const FITTED_CALIBRATION: CalibrationSet | null = {
  temperature_2m: {
    bands: [
      {
        bins: [
          {
            raw: 0.006204459928553848,
            p: 0.9660309034297914,
          },
          {
            raw: 0.09670980833602837,
            p: 0.9660309034297914,
          },
          {
            raw: 0.1800321042336049,
            p: 0.9660309034297914,
          },
          {
            raw: 0.24685569756251677,
            p: 0.9737103174603176,
          },
          {
            raw: 0.36844761384532276,
            p: 0.9975775193798451,
          },
        ],
        n: 192,
        source: "builtin",
      },
      {
        bins: [
          {
            raw: 0.15244471711016605,
            p: 0.8506944444444444,
          },
          {
            raw: 0.3458186176229335,
            p: 0.9459325396825397,
          },
          {
            raw: 0.44238809259245737,
            p: 0.946569395904944,
          },
          {
            raw: 0.5140899651532685,
            p: 0.946569395904944,
          },
          {
            raw: 0.6069774576536597,
            p: 0.9704457364341085,
          },
        ],
        n: 192,
        source: "builtin",
      },
      {
        bins: [
          {
            raw: 0.32552864818790955,
            p: 0.6584699453551912,
          },
          {
            raw: 0.4993485663291323,
            p: 0.8245574274130593,
          },
          {
            raw: 0.5794839750676481,
            p: 0.8245574274130593,
          },
          {
            raw: 0.632312567820854,
            p: 0.8245574274130593,
          },
          {
            raw: 0.7122426479396279,
            p: 0.8245574274130593,
          },
        ],
        n: 288,
        source: "builtin",
      },
      {
        bins: [
          {
            raw: 0.24992416054602606,
            p: 0.44672131147540983,
          },
          {
            raw: 0.44807416417264306,
            p: 0.4674913204423701,
          },
          {
            raw: 0.5700946101546872,
            p: 0.4674913204423701,
          },
          {
            raw: 0.6594525980677252,
            p: 0.6330645161290323,
          },
          {
            raw: 0.7575993052402147,
            p: 0.7943548387096774,
          },
        ],
        n: 288,
        source: "builtin",
      },
    ],
  },
  precipitation: {
    bands: [
      {
        bins: [
          {
            raw: 0.7795483596526441,
            p: 0.7098214285714285,
          },
          {
            raw: 0.9470156981737611,
            p: 0.7098214285714285,
          },
          {
            raw: 0.9970167829274366,
            p: 0.9879807692307693,
          },
        ],
        n: 96,
        source: "builtin",
      },
      {
        bins: [
          {
            raw: 0.8658372591318088,
            p: 0.7475198412698413,
          },
          {
            raw: 0.9547528328016436,
            p: 0.7475198412698413,
          },
          {
            raw: 0.9855386723931301,
            p: 0.8464147286821706,
          },
          {
            raw: 0.9989597776632398,
            p: 0.9555041152263374,
          },
        ],
        n: 192,
        source: "builtin",
      },
      {
        bins: [
          {
            raw: 0.8607237974047479,
            p: 0.7273377429056718,
          },
          {
            raw: 0.9465235923801473,
            p: 0.7273377429056718,
          },
          {
            raw: 0.9809766416151532,
            p: 0.7273377429056718,
          },
          {
            raw: 0.9947640691807955,
            p: 0.9238351254480287,
          },
          {
            raw: 0.9999831277379394,
            p: 0.9883512544802867,
          },
        ],
        n: 288,
        source: "builtin",
      },
      {
        bins: [
          {
            raw: 0.847365766028673,
            p: 0.5941902142202217,
          },
          {
            raw: 0.9420937111521018,
            p: 0.5941902142202217,
          },
          {
            raw: 0.9732883666468782,
            p: 0.5941902142202217,
          },
          {
            raw: 0.98961776785065,
            p: 0.7383512544802867,
          },
          {
            raw: 0.999221959009796,
            p: 0.9480286738351255,
          },
        ],
        n: 288,
        source: "builtin",
      },
    ],
  },
};

export const DEFAULT_CALIBRATION_META = currentAnalysis(FITTED_META, FITTED_META?.analysisVersion);
export const DEFAULT_CALIBRATION = DEFAULT_CALIBRATION_META ? FITTED_CALIBRATION : null;
