// GENERATED by scripts/fit-default-calibration.ts — do not edit by hand.
// The shipped default calibration tier (ADR 0010): curves fitted offline from
// verification samples at global reference locations, slotted into the ladder
// below the device tiers. Regenerate with:
//   pnpm dlx tsx scripts/fit-default-calibration.ts

import type { CalibrationSet } from "@/domain/calibration";

export interface DefaultCalibrationMeta {
  generatedAt: string;
  locations: string[];
  runDates: string[];
  /** Calibration points consumed, per variable. */
  points: Record<string, number>;
}

export const DEFAULT_CALIBRATION_META: DefaultCalibrationMeta | null = {
  generatedAt: "2026-07-10T17:11:24.293Z",
  locations: ["Innsbruck", "London", "Lisbon", "Oslo", "New York", "Denver", "Seattle", "Tokyo", "Singapore", "Sydney", "São Paulo", "Cape Town"],
  runDates: ["2025-09-15", "2025-10-26", "2025-12-05", "2026-01-15", "2026-02-24", "2026-04-06", "2026-05-16", "2026-06-26"],
  points: {
    temperature_2m: 406,
    precipitation: 483,
  },
};

export const DEFAULT_CALIBRATION: CalibrationSet | null = {
  temperature_2m: {
    bands: [
      {
        bins: [
          {
            raw: 0.004128225013849255,
            p: 0.8288633461047255,
          },
          {
            raw: 0.10132870534174647,
            p: 0.8288633461047255,
          },
          {
            raw: 0.25528911615429567,
            p: 0.8288633461047255,
          },
          {
            raw: 0.3333333333333331,
            p: 0.8288633461047255,
          },
          {
            raw: 0.34448411314727306,
            p: 0.9064039408866995,
          },
        ],
        n: 116,
        source: "builtin",
      },
      {
        bins: [
          {
            raw: 0.09660616149365127,
            p: 0.6768837803320561,
          },
          {
            raw: 0.3229093005006901,
            p: 0.806513409961686,
          },
          {
            raw: 0.3333333333333331,
            p: 0.806513409961686,
          },
          {
            raw: 0.39994342119639864,
            p: 0.8620689655172413,
          },
          {
            raw: 0.545329415412321,
            p: 0.938423645320197,
          },
        ],
        n: 116,
        source: "builtin",
      },
      {
        bins: [
          {
            raw: 0.20047790959037526,
            p: 0.5719903206291591,
          },
          {
            raw: 0.33333333333333337,
            p: 0.6214264662540525,
          },
          {
            raw: 0.357068933816005,
            p: 0.6214264662540525,
          },
          {
            raw: 0.5189682046918277,
            p: 0.7111700559976422,
          },
          {
            raw: 0.660838260054006,
            p: 0.8906572354848217,
          },
        ],
        n: 174,
        source: "builtin",
      },
    ],
  },
  precipitation: {
    bands: [
      {
        bins: [
          {
            raw: 0.317610305594978,
            p: 0.8466265034638106,
          },
          {
            raw: 0.329861111111111,
            p: 0.8466265034638106,
          },
          {
            raw: 0.561681753637532,
            p: 0.8466265034638106,
          },
          {
            raw: 0.9177224977527744,
            p: 0.8466265034638106,
          },
          {
            raw: 0.9787105633743514,
            p: 0.8881340579710145,
          },
        ],
        n: 138,
        source: "builtin",
      },
      {
        bins: [
          {
            raw: 0.3333333333333332,
            p: 0.7601683029453016,
          },
          {
            raw: 0.3333333333333332,
            p: 0.9020788624343093,
          },
          {
            raw: 0.6262664564098089,
            p: 0.9020788624343093,
          },
          {
            raw: 0.9698056618613032,
            p: 0.9020788624343093,
          },
          {
            raw: 0.9984023566857536,
            p: 0.9864130434782609,
          },
        ],
        n: 138,
        source: "builtin",
      },
      {
        bins: [
          {
            raw: 0.3333333333333334,
            p: 0.6896403650026838,
          },
          {
            raw: 0.3333333333333334,
            p: 0.7287418910668296,
          },
          {
            raw: 0.6581311076425256,
            p: 0.7287418910668296,
          },
          {
            raw: 0.9668341084496329,
            p: 0.7287418910668296,
          },
          {
            raw: 0.9948112683541872,
            p: 0.9137786179374082,
          },
        ],
        n: 207,
        source: "builtin",
      },
    ],
  },
};
