// GENERATED by scripts/fit-default-weights.ts — do not edit by hand.
// The shipped default weight tier (ADR 0011): per-model, per-lead-band weight
// multipliers fitted offline from verification runs at global reference
// locations, pooled across all of them. This is the app's lead-time weighting —
// it REPLACED the old hand-tuned per-class decay curves — resolved by
// weightLadder.resolveMultiplier (per-model → per-class → 1, each band
// independently). Regenerate with:
//   pnpm dlx tsx scripts/fit-default-weights.ts

import type { BuiltinWeightMeta, BuiltinWeightSet } from "@/domain/weightLadder";

import { currentAnalysis } from "./version";

const FITTED_META: BuiltinWeightMeta | null = {
  analysisVersion: 4,
  generatedAt: "2026-09-13T13:33:13.053Z",
  locations: ["Munich", "London", "Lisbon", "Oslo", "New York", "Denver", "Seattle", "Tokyo", "Singapore", "Sydney", "São Paulo", "Cape Town"],
  runDates: [
    "2026-04-02",
    "2026-04-08",
    "2026-04-15",
    "2026-04-21",
    "2026-04-28",
    "2026-05-04",
    "2026-05-11",
    "2026-05-17",
    "2026-05-23",
    "2026-05-30",
    "2026-06-05",
    "2026-06-12",
    "2026-06-18",
    "2026-06-25",
    "2026-07-01",
    "2026-07-08",
    "2026-07-14",
    "2026-07-20",
    "2026-07-27",
    "2026-08-02",
    "2026-08-09",
    "2026-08-15",
    "2026-08-22",
    "2026-08-28",
  ],
  bands: [
    {
      label: "0–2d",
      start: 0,
      end: 48,
    },
    {
      label: "2–4d",
      start: 48,
      end: 96,
    },
    {
      label: "4–7d",
      start: 96,
      end: 168,
    },
    {
      label: "7–10d",
      start: 168,
      end: 240,
    },
  ],
};

const FITTED_WEIGHTS: BuiltinWeightSet | null = {
  perModel: {
    ecmwf_ifs: [1.0304, 0.84, 0.84, 1.4],
    gfs_seamless: [0.29439999999999994, 0.27999999999999997, 0.27999999999999997, 0.3999999999999999],
    ukmo_seamless: [0.27999999999999997, 0.29439999999999994, 0.29439999999999994, 0.29439999999999994],
    meteofrance_seamless: [0.4416, 0.36, 0.36, null],
    cma_grapes_global: [1.68, 0.72, 0.72, null],
    icon_global: [0.6, 0.6, 0.4416, 0.84],
    icon_eu: [0.36, 0.4416, 1.08, null],
    icon_d2: [0.27999999999999997, 0.27999999999999997, null, null],
    knmi_harmonie_arome_europe: [0.27999999999999997, 0.5599999999999998, null, null],
    dmi_harmonie_arome_europe: [0.4416, 0.6, null, null],
    meteoswiss_icon_seamless: [1.68, 1.84, 1.84, null],
    geosphere_arome_austria: [0.4416, 1.08, null, null],
    ecmwf_aifs025_single: [1.8, 1.96, 1.96, 1.96],
    gfs_graphcast025: [0.3999999999999999, 0.5599999999999998, 0.5599999999999998, 0.27999999999999997],
    ncep_aigfs025: [0.736, 1.4, 1.8, 1],
    ncep_hgefs025_ensemble_mean: [0.6, 1.08, 0.6, 0.6],
    jma_seamless: [0.29439999999999994, 0.27999999999999997, 0.27999999999999997, 0.3999999999999999],
    metno_nordic: [0.3999999999999999, 0.7199999999999999, null, null],
  },
  perClass: {
    global: [1.08, 0.4416, 0.36, 0.6],
    "regional-mid": [0.29439999999999994, 0.27999999999999997, 0.29439999999999994, 0.27999999999999997],
    "regional-cam": [0.5599999999999998, 0.3999999999999999, 0.29439999999999994, null],
    ai: [1.8, 1.8, 1.96, 1.08],
    "ensemble-mean": [0.3999999999999999, 0.7199999999999999, 0.7199999999999999, 0.3999999999999999],
  },
  meta: {
    analysisVersion: 4,
    generatedAt: "2026-09-13T13:33:13.053Z",
    locations: ["Munich", "London", "Lisbon", "Oslo", "New York", "Denver", "Seattle", "Tokyo", "Singapore", "Sydney", "São Paulo", "Cape Town"],
    runDates: [
      "2026-04-02",
      "2026-04-08",
      "2026-04-15",
      "2026-04-21",
      "2026-04-28",
      "2026-05-04",
      "2026-05-11",
      "2026-05-17",
      "2026-05-23",
      "2026-05-30",
      "2026-06-05",
      "2026-06-12",
      "2026-06-18",
      "2026-06-25",
      "2026-07-01",
      "2026-07-08",
      "2026-07-14",
      "2026-07-20",
      "2026-07-27",
      "2026-08-02",
      "2026-08-09",
      "2026-08-15",
      "2026-08-22",
      "2026-08-28",
    ],
    bands: [
      {
        label: "0–2d",
        start: 0,
        end: 48,
      },
      {
        label: "2–4d",
        start: 48,
        end: 96,
      },
      {
        label: "4–7d",
        start: 96,
        end: 168,
      },
      {
        label: "7–10d",
        start: 168,
        end: 240,
      },
    ],
  },
};

export const DEFAULT_WEIGHTS_META = currentAnalysis(FITTED_META, FITTED_META?.analysisVersion);
export const DEFAULT_WEIGHTS = DEFAULT_WEIGHTS_META ? FITTED_WEIGHTS : null;
