// GENERATED by scripts/fit-default-weights.ts — do not edit by hand.
// The shipped default weight tier (ADR 0011): per-model, per-lead-band weight
// multipliers fitted offline from verification runs at global reference
// locations, pooled across all of them. This is the app's lead-time weighting —
// it REPLACED the old hand-tuned per-class decay curves — resolved by
// weightLadder.resolveMultiplier (per-model → per-class → 1, each band
// independently). Regenerate with:
//   pnpm dlx tsx scripts/fit-default-weights.ts

import type { BuiltinWeightMeta, BuiltinWeightSet } from "@/domain/weightLadder";

export const DEFAULT_WEIGHTS_META: BuiltinWeightMeta | null = {
  generatedAt: "2026-07-12T03:21:14.328Z",
  locations: ["Munich", "London", "Lisbon", "Oslo", "New York", "Denver", "Seattle", "Tokyo", "Singapore", "Sydney", "São Paulo", "Cape Town"],
  runDates: [
    "2026-04-02",
    "2026-04-06",
    "2026-04-09",
    "2026-04-13",
    "2026-04-17",
    "2026-04-20",
    "2026-04-24",
    "2026-04-28",
    "2026-05-02",
    "2026-05-05",
    "2026-05-09",
    "2026-05-13",
    "2026-05-16",
    "2026-05-20",
    "2026-05-24",
    "2026-05-27",
    "2026-05-31",
    "2026-06-04",
    "2026-06-08",
    "2026-06-11",
    "2026-06-15",
    "2026-06-19",
    "2026-06-22",
    "2026-06-26",
  ],
  bands: [
    {
      label: "0–2d",
      start: 0,
      end: 48,
    },
    {
      label: "2–4d",
      start: 48,
      end: 96,
    },
    {
      label: "4–7d",
      start: 96,
      end: 168,
    },
    {
      label: "7–10d",
      start: 168,
      end: 240,
    },
  ],
};

export const DEFAULT_WEIGHTS: BuiltinWeightSet | null = {
  perModel: {
    ecmwf_ifs: [1.96, 1.3248000000000002, 1.08, 1.3248000000000002],
    gfs_seamless: [0.3999999999999999, 0.29439999999999994, 0.27999999999999997, 0.7199999999999999],
    ukmo_seamless: [0.27999999999999997, 0.3999999999999999, 0.3999999999999999, 0.27999999999999997],
    meteofrance_seamless: [0.29439999999999994, 0.3999999999999999, 0.3999999999999999, null],
    cma_grapes_global: [0.7199999999999999, 0.3999999999999999, 0.3999999999999999, null],
    icon_global: [0.7199999999999999, 0.29439999999999994, 0.27999999999999997, 0.3999999999999999],
    icon_eu: [0.36, 0.36, 0.36, null],
    icon_d2: [0.27999999999999997, 0.27999999999999997, null, null],
    knmi_harmonie_arome_europe: [0.3999999999999999, 0.3999999999999999, null, null],
    dmi_harmonie_arome_europe: [0.3999999999999999, 0.7199999999999999, null, null],
    meteoswiss_icon_seamless: [0.6, 0.6, 1.8, null],
    geosphere_arome_austria: [0.72, 0.72, null, null],
    ecmwf_aifs025_single: [1.8, 1.96, 1.8, 1.8],
    gfs_graphcast025: [0.6, 0.36, 0.36, 0.4416],
    ncep_aigfs025: [1.8, 1.3248000000000002, 1.8, 1.8],
    ncep_hgefs025_ensemble_mean: [1.12, 0.8, 0.8, 0.8],
    jma_seamless: [0.3999999999999999, 0.3999999999999999, 0.3999999999999999, 0.3999999999999999],
    metno_nordic: [0.4416, 1.08, null, null],
  },
  perClass: {
    global: [0.84, 0.36, 0.4416, 0.4416],
    "regional-mid": [0.29439999999999994, 0.27999999999999997, 0.27999999999999997, 0.27999999999999997],
    "regional-cam": [0.3999999999999999, 0.27999999999999997, 0.7199999999999999, null],
    ai: [1.2, 1.84, 1.2, 1.2],
    "ensemble-mean": [1, 0.6, 1, 1],
  },
  meta: {
    generatedAt: "2026-07-12T03:21:14.328Z",
    locations: ["Munich", "London", "Lisbon", "Oslo", "New York", "Denver", "Seattle", "Tokyo", "Singapore", "Sydney", "São Paulo", "Cape Town"],
    runDates: [
      "2026-04-02",
      "2026-04-06",
      "2026-04-09",
      "2026-04-13",
      "2026-04-17",
      "2026-04-20",
      "2026-04-24",
      "2026-04-28",
      "2026-05-02",
      "2026-05-05",
      "2026-05-09",
      "2026-05-13",
      "2026-05-16",
      "2026-05-20",
      "2026-05-24",
      "2026-05-27",
      "2026-05-31",
      "2026-06-04",
      "2026-06-08",
      "2026-06-11",
      "2026-06-15",
      "2026-06-19",
      "2026-06-22",
      "2026-06-26",
    ],
    bands: [
      {
        label: "0–2d",
        start: 0,
        end: 48,
      },
      {
        label: "2–4d",
        start: 48,
        end: 96,
      },
      {
        label: "4–7d",
        start: 96,
        end: 168,
      },
      {
        label: "7–10d",
        start: 168,
        end: 240,
      },
    ],
  },
};
